### ISSUE TITLE
Deploy failed after long time stay on Starting service with './app' section

### ISSUE THREAD

**Issue by bugbounted** [pyfbsdk59/Golang-ChatGPT-TelegramBot-Render#1]
Hi [pyfbsdk59](https://github.com/pyfbsdk59),
after fork your repo & import project as web services & set 3 env (OPENAI_TOKEN , OPENAI_MAXTOKENS , TELEGRAM_BOT_TOKEN) in Advanced section of pre-build page & start building , freeze on section "Starting service with './app'" & after long time deploy status changed to failed !!

also failed deploy log is :
```
Jan. 6 08:43:48 PM  ==> Cloning from https://github.com/bugbounted/Golang-ChatGPT-TelegramBot-Render...
Jan. 6 08:43:49 PM  ==> Checking out commit 950e9c3b471cc43a9c7083c2cb4c5b7d932c8c74 in branch main
Jan. 6 08:43:52 PM  ==> Running build command 'go build -tags netgo -ldflags '-s -w' -o app'...
Jan. 6 08:43:52 PM  go: downloading github.com/yanzay/tbot/v2 v2.2.0
Jan. 6 08:43:52 PM  go: downloading github.com/sashabaranov/go-gpt3 v0.0.0-20230103131550-2c55a49a3495
Jan. 6 08:43:57 PM  ==> Generating container image from build. This may take a few minutes...
Jan. 6 08:44:45 PM  ==> Uploading build...
Jan. 6 08:45:00 PM  ==> Build uploaded in 12s
Jan. 6 08:45:00 PM  ==> Build successful 🎉
Jan. 6 08:45:00 PM  ==> Deploying...
Jan. 6 08:45:16 PM  ==> Starting service with './app'
```

waiting for your response
finest regards

**Comment by pyfbsdk59** [comment]
Did you add your Render URL in main.go file? It is a little tricky, though. Before setting the environment variables, you can get to know your Render URL, you have to add it to he 44th line of main.go file. Import the project on Render again, I think it will be fine. You can also set you teltegram webhook first according to my steps. Thank you!

**Comment by bugbounted** [comment]
Hello again [pyfbsdk59](https://github.com/pyfbsdk59),
I'm edited 44th line of main.go file & then deployed & after that not work !!!
also trying to set telegram webhook using your method too but all the same & nothing work :(
please if it's possible make video from your deploy steps or make dockerfile on root project for try to deploy on other serverless paas like [doprax](https://www.doprax.com/).
waiting for your commit/s to fix it at soonest time possible .
regards .mohamad

**Comment by pyfbsdk59** [comment]
Hi, I manually redeploy the code, and it can be deployed eventually. It acutually took some time to finish deploying.
The reason of long waiting is unknown.
After deploying, when you ask the bot questions, you have to use a sentence that starts with "human: ".
You can see my two demo pics on README.MD
It is working fine now. Please try again. Thank you!
