### ISSUE TITLE
problem in "starting service with ./app"

### ISSUE THREAD

**Issue by meisam0083** [pyfbsdk59/Golang-ChatGPT-TelegramBot-Render#2]
Hi,

I created the source on the render,
It takes some time, then it gives an error.
I also added a site hook to mine.go

Please advise, thanks.

![Screenshot_۲۰۲۳-۰۱-۲۵-۱۹-۱۸-۴۶-۸۲۴-edit_com opera browser](https://user-images.githubusercontent.com/13857970/214611324-dc30884c-dcf6-4183-9465-021c2e644c09.jpg)

**Comment by meisam0083** [comment]
I also configured as below.


![Screenshot_۲۰۲۳-۰۱-۲۵-۱۹-۲۷-۳۴-۵۸۲-edit_com opera browser](https://user-images.githubusercontent.com/13857970/214612093-aa58ee81-3c1c-4882-a2d5-0c9c1351e93d.jpg)

**Comment by pyfbsdk59** [comment]
Did you add your own Render URL in line 44 of main.go file?
Maybe you should try again.
Envrironment variables look fine!
Please check that first. Thank you!

**Comment by meisam0083** [comment]
I this had left Rander URL in line 44 of Main.go file,
But it failed again, when I set OPENAI_MAXTOKENS to 100,
it was created without error, it is live now, there is no problem,
but inside Telegram, the bot does not work.

**Comment by pyfbsdk59** [comment]
Did you set the webhook according to my README.MD?

**Comment by meisam0083** [comment]
Yes, no problem, the bot is not working 

![IMG_۲۰۲۳۰۱۲۸_۰۹۰۸۱۷](https://user-images.githubusercontent.com/13857970/215248207-e6ba8901-a1dc-4ac6-b692-d36199ce23ab.jpg)

**Comment by pyfbsdk59** [comment]
I will try to deploy one more time to find out what's wrong.

**Comment by meisam0083** [comment]
OK, thank you

**Comment by pyfbsdk59** [comment]
Hi, I manually redeploy the code, and it can be deployed eventually. It acutually took some time to finish deploying.
The reason of long waiting is unknown.
After deploying, when you ask the bot questions, you have to use a sentence that starts with "human: ".
You can see my two demo pics on README.MD
It is working fine now. Please try again. Thank you!

**Comment by meisam0083** [comment]
Hi,
I will do it again and let you know the result, thanks.

**Comment by meisam0083** [comment]
By writing "human:", the code works correctly. Thank you.🙏

**Comment by meisam0083** [comment]
Excuse me,
how do I delete the "human:"?
because every time I want to write a word, I have to write the "human:".

I from inside main.go file, deleted the word "human:", but nothing changed.

**Comment by pyfbsdk59** [comment]
The original code I used have to be provided some key words to intriger the bot reaction.
You have to test for yourself to find a way without these key words. Thank you!
"human:" key word can be changed into any other key words. You can make it shorter.
